// <auto-generated />
using System;
using Dominodo.Users.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dominodo.Users.Persistence.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20260722202859_GranularOperationsPermissions")]
    partial class GranularOperationsPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dominodo.Users.Domain.Authentication.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", "users");
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Authentication.VerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Phone", "Purpose");

                    b.ToTable("VerificationCodes", "users");
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Memberships.Membership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("InvitedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("JoinedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId", "TenantId")
                        .IsUnique();

                    b.ToTable("Memberships", "users");
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Roles.Permission", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", "users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "users.manage",
                            Description = "Gestionar usuarios.",
                            Group = "Usuarios"
                        },
                        new
                        {
                            Id = 2,
                            Code = "roles.manage",
                            Description = "Gestionar roles y permisos.",
                            Group = "Usuarios"
                        },
                        new
                        {
                            Id = 9,
                            Code = "settings.view",
                            Description = "Ver configuración.",
                            Group = "Administración"
                        },
                        new
                        {
                            Id = 10,
                            Code = "tenants.create",
                            Description = "Crear conjuntos residenciales.",
                            Group = "Plataforma"
                        },
                        new
                        {
                            Id = 11,
                            Code = "tenants.view",
                            Description = "Ver conjuntos residenciales.",
                            Group = "Plataforma"
                        },
                        new
                        {
                            Id = 12,
                            Code = "tenants.edit",
                            Description = "Editar conjuntos residenciales.",
                            Group = "Plataforma"
                        },
                        new
                        {
                            Id = 13,
                            Code = "memberships.manage",
                            Description = "Gestionar membresías de un conjunto.",
                            Group = "Membresías"
                        },
                        new
                        {
                            Id = 14,
                            Code = "apartments.create",
                            Description = "Crear apartamentos.",
                            Group = "Apartamentos"
                        },
                        new
                        {
                            Id = 15,
                            Code = "apartments.view",
                            Description = "Ver apartamentos.",
                            Group = "Apartamentos"
                        },
                        new
                        {
                            Id = 16,
                            Code = "apartments.edit",
                            Description = "Editar apartamentos.",
                            Group = "Apartamentos"
                        },
                        new
                        {
                            Id = 17,
                            Code = "settings.create",
                            Description = "Crear configuración.",
                            Group = "Administración"
                        },
                        new
                        {
                            Id = 18,
                            Code = "settings.edit",
                            Description = "Editar configuración.",
                            Group = "Administración"
                        },
                        new
                        {
                            Id = 19,
                            Code = "notifications.view",
                            Description = "Ver notificaciones.",
                            Group = "Notificaciones"
                        },
                        new
                        {
                            Id = 20,
                            Code = "notifications.create",
                            Description = "Crear notificaciones.",
                            Group = "Notificaciones"
                        },
                        new
                        {
                            Id = 21,
                            Code = "notifications.edit",
                            Description = "Editar notificaciones.",
                            Group = "Notificaciones"
                        },
                        new
                        {
                            Id = 22,
                            Code = "users.view",
                            Description = "Ver usuarios.",
                            Group = "Usuarios"
                        },
                        new
                        {
                            Id = 23,
                            Code = "requests.view",
                            Description = "Ver solicitudes (PQRS).",
                            Group = "Solicitudes"
                        },
                        new
                        {
                            Id = 24,
                            Code = "requests.edit",
                            Description = "Editar solicitudes (PQRS).",
                            Group = "Solicitudes"
                        },
                        new
                        {
                            Id = 25,
                            Code = "requests.manage",
                            Description = "Gestionar el ciclo de vida de solicitudes (PQRS).",
                            Group = "Solicitudes"
                        },
                        new
                        {
                            Id = 26,
                            Code = "requests.delete",
                            Description = "Eliminar o cancelar solicitudes (PQRS).",
                            Group = "Solicitudes"
                        },
                        new
                        {
                            Id = 27,
                            Code = "deliveries.view",
                            Description = "Ver paquetería.",
                            Group = "Paquetería"
                        },
                        new
                        {
                            Id = 28,
                            Code = "deliveries.edit",
                            Description = "Editar y cambiar el estado de paquetería.",
                            Group = "Paquetería"
                        },
                        new
                        {
                            Id = 29,
                            Code = "deliveries.create",
                            Description = "Registrar paquetería.",
                            Group = "Paquetería"
                        },
                        new
                        {
                            Id = 30,
                            Code = "visits.view",
                            Description = "Ver visitas.",
                            Group = "Visitas"
                        },
                        new
                        {
                            Id = 31,
                            Code = "visits.edit",
                            Description = "Editar y cambiar el estado de visitas.",
                            Group = "Visitas"
                        },
                        new
                        {
                            Id = 32,
                            Code = "visits.create",
                            Description = "Registrar visitas.",
                            Group = "Visitas"
                        },
                        new
                        {
                            Id = 33,
                            Code = "announcements.view",
                            Description = "Ver comunicados (incl. borradores).",
                            Group = "Comunicaciones"
                        },
                        new
                        {
                            Id = 34,
                            Code = "announcements.edit",
                            Description = "Editar, publicar y archivar comunicados.",
                            Group = "Comunicaciones"
                        },
                        new
                        {
                            Id = 35,
                            Code = "announcements.create",
                            Description = "Crear borradores de comunicados.",
                            Group = "Comunicaciones"
                        });
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Roles.PlatformRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("PlatformRoleAssignments", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000101"),
                            RoleId = 1,
                            UserId = new Guid("00000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", "users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Acceso total a la plataforma (cross-tenant).",
                            IsSystem = true,
                            Name = "SuperAdmin",
                            Scope = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Administra un conjunto residencial.",
                            IsSystem = true,
                            Name = "Administrador",
                            Scope = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "Asiste en la administración del conjunto.",
                            IsSystem = true,
                            Name = "AsistenteAdministracion",
                            Scope = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Personal de portería y seguridad.",
                            IsSystem = true,
                            Name = "Vigilante",
                            Scope = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "Residente de un apartamento.",
                            IsSystem = true,
                            Name = "Residente",
                            Scope = 1
                        });
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Roles.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", "users");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 13
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 26
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 19
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 20
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 23
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 24
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 32
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 33
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 34
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 35
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 27
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 28
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 29
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 30
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 31
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 32
                        });
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("PhoneVerifiedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Profile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users", "users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "superadmin@dominodo.local",
                            FirstName = "Super",
                            LastName = "Admin",
                            PasswordHash = "$2b$11$3qiA6Ogz7cU0k/slUmOy5uiFJOvKStCMp0VjaMPqiw7ry8PxOm71i",
                            Phone = "+1111111",
                            PhoneVerifiedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PreferredLanguage = "es",
                            Status = "Active",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Memberships.Membership", b =>
                {
                    b.HasOne("Dominodo.Users.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dominodo.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Roles.PlatformRoleAssignment", b =>
                {
                    b.HasOne("Dominodo.Users.Domain.Roles.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Roles.RolePermission", b =>
                {
                    b.HasOne("Dominodo.Users.Domain.Roles.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dominodo.Users.Domain.Roles.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dominodo.Users.Domain.Roles.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
